# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Mission-X for Skunkcrafts

## Auto run workflow, only if we have a tag that starts with v*
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build_and_copy:
#    Execute only if we have "push + tag name that starts with "v"
#    if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release Folder
        run: mkdir -p missionx

      - name: Copy Files to Release Folder
        run: |
          cp -r ./* missionx/
          # Exclude the .git directory if you don't need it in the release
          rm -rf missionx/.git

      - name: List Contents of Release Folder
        run: ls -R missionx/

      # Optional: Add steps here to create a release, upload artifacts, etc.
      # For example, to create a simple artifact:
      - name: Upload Release Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: missionx-${github.ref_name}
          path: missionx